services:
  scrum-cards:
    container_name: scrum-cards
    image: ${IMAGE}
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrum-cards.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.scrum-cards.entrypoints=websecure"
      - "traefik.http.routers.scrum-cards.tls=true"
      - "traefik.http.routers.scrum-cards.tls.certresolver=letencrypt"
      - "traefik.http.services.scrum-cards.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    name: web
    external: true
